Test notebooks github actions
atoti/notebooks pull request #145
Opened 2021-06-14 16:00 UTC by bloussou

2021-06-15 12:56 UTC, tibdex requested changes
It's gonna be nice 👍🏻 .

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test.yaml
> +# poetry run jupyter nbconvert --to notebook  --execute notebooks/baseball/main.ipynb --inplace
```suggestion
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test.yaml
> +        shell: bash
```suggestion
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test.yaml
> +        shell: bash
```suggestion
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test.yaml
> +      - name: Test notebooks execution
```suggestion
      - name: Run notebooks
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test.yaml
> +        run: poetry run python .github/workflows/test_notebooks.py
```suggestion
        run: poetry run python .github/workflows/execute_notebooks.py
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test_notebooks.py
> +"""Scrip to execute all the notebooks."""
```suggestion
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test_notebooks.py
> +NOTEBOOKS_FOLDER = "notebooks/"
```suggestion
NOTEBOOKS_DIRECTORY = Path("notebooks")
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test_notebooks.py
> +# List of notebooks used to create files containing data, must not be tested
```suggestion
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test_notebooks.py
> +    "notebooks/twitter/03_cryptocurrency_mining.ipynb",
Use `Path` concatenation such as `NOTEBOOKS_DIRECTORY / "customer-churn" / "0_prepare_data.ipynb"`.

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test_notebooks.py
> +# List of notebooks with errors in the CI
```suggestion
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test_notebooks.py
> +NOTEBOOKS_WITH_FAILURES = [
```suggestion
NOTEBOOKS_WITH_ERRORS = [
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test_notebooks.py
> +    "notebooks/real-time-risk/main.ipynb",  # SyntaxError: invalid syntax (simple.py, line 54) TO FIX
Same thing, use `Path`.

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test_notebooks.py
> +        for notebook_path in glob.glob("notebooks/**/*.ipynb")
```suggestion
        for notebook_path in NOTEBOOKS_DIRECTORY.glob("**/*.ipynb")
```

2021-06-15 12:56 UTC, tibdex commented on .github/workflows/test_notebooks.py
> +    logging.info(f"Execution of {notebook_path} succeed")
The best practice is to restructure the code like this:

```python
def execute_notebooks():
  notebooks_path = sorted(
  ...
  logging.info(f"Successfully executed {notebook_path}")


if __name__ == "__main__":
  logging.basicConfig(format="%(asctime)s %(message)s", level=logging.INFO)
  execute_notebooks()
```

2021-06-15 12:56 UTC, tibdex commented on .gitignore
> +.vscode/
This is not project specific so it's the contributor's responsibility to configure Git globally to ignore these files.

2021-06-15 12:56 UTC, tibdex commented on .vscode/settings.json
> +}
We shouldn't add this file.

2021-06-15 13:38 UTC, bloussou commented
I've added a section in CONTRIBUTING.md

2021-06-16 11:09 UTC, tibdex commented on CONTRIBUTING.md
> +This repository is tested using [github actions](.github/workflows/test.yaml).
```suggestion
This repository is tested with a [Github Action](.github/workflows/test.yaml).
```

2021-06-16 11:09 UTC, tibdex commented on CONTRIBUTING.md
> +- Reformat notebooks using black :
```suggestion
These commands can be used while developing: 

- Reformat notebooks using black:
```

2021-06-16 11:09 UTC, tibdex commented on CONTRIBUTING.md
> +  `poetry run black-nb notebooks/`
```suggestion
```bash
poetry run black-nb notebooks/
```
```

2021-06-16 11:09 UTC, tibdex commented on CONTRIBUTING.md
> +- Check notebook execution:
```suggestion
- Execute all the notebooks:
```

2021-06-16 11:09 UTC, tibdex commented on CONTRIBUTING.md
> +  `poetry run python .github/workflows/execute_notebooks.py`
Use ```bash``` here too. Seeing the path to the Python file here, it would be nicer to move it to a place like `tests/execute_notebooks.py` rather than inside `.github/workflows`.

2021-06-16 11:09 UTC, tibdex commented on CONTRIBUTING.md
> +Checkout [poetry](https://python-poetry.org/docs/) for more info.
Do you have something specific in mind here? If no, I would rather remove this line.

2021-06-16 11:09 UTC, tibdex commented on CONTRIBUTING.md
> +Add notebooks creating data or preprocessing data to the [DATA_PREPROCESSING_NOTEBOOKS list](.github/workflows/execute_notebooks.py) if the execution of these notebooks take too much time or need spe
```suggestion
```

2021-06-16 11:09 UTC, tibdex commented on pyproject.toml
> +description = "Official atoti notebooks gallery"
```suggestion
description = "Gallery of atoti notebooks"
```

2021-06-16 11:09 UTC, tibdex commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
```suggestion
authors = ["atoti <contact@atoti.io>"]
```

2021-06-16 11:09 UTC, tibdex commented on pyproject.toml
> +atoti = {extras = ["jupyterlab", "kafka", "aws", "azure", "gcp"], version = "^0.5.5"}
Nice usage of `extras` 👍🏻 .

2021-06-16 11:09 UTC, tibdex commented on pyproject.toml
> +[tool.poetry.dev-dependencies]
Dependencies used in notebooks are not `dev-dependencies`, they are regular `dependencies`. I guess only `black-nb` should be in this list for now.

2021-06-16 15:13 UTC, tibdex approved these changes
:octocat:

2021-06-16 15:13 UTC, tibdex commented on pyproject.toml
> +black-nb = "^0.5.0"
Isn't `black` missing here (we should not rely on the fact that it might be a transitive dependency)?

2021-06-17 01:20 UTC, HuifangYeo approved these changes
OK

2021-06-17 01:21 UTC, merged