Initial update
atoti/notebooks pull request #276
Opened 2021-10-08 11:59 UTC by rvs36

Initial update

2021-10-08 19:34 UTC, printhellohetal commented on notebooks/object-detection/ai/detect_masked_face_from_video.py
> +import cv2
Looks like you need to add a line for installing cv2 at the beginning of your notebook, since this fails the checks.

2021-10-11 12:35 UTC, bloussou commented on pyproject.toml
> +poetry = "^1.1.11"
why are you adding poetry here ?

2021-10-11 12:37 UTC, bloussou commented on notebooks/object-detection/ai/detect_masked_face_from_video.py
> +# import some common detectron2 utilities
This can be removed since it is obvious

2021-10-11 18:52 UTC, printhellohetal commented on pyproject.toml
>  openpyxl = "^3.0.7"
Additional libraries seem to be needed, including Torchvision and detectron2 for your notebook to run; not sure what version specifically.

2021-10-13 08:20 UTC, bloussou requested changes

2021-10-13 08:22 UTC, bloussou commented on poetry.lock
> +version = "0.6.1"
It is creating this issue `TypeError: entry_points() got an unexpected keyword argument 'group'`

2021-10-13 20:43 UTC, closed without merging